### ISSUE TITLE
JS16_Bootloader fails to program when using a USB 3 port

### ISSUE THREAD

**Issue by tchebb** [podonoghue/usbdm-eclipse-makefiles-build#10] opened 2019-09-09 05:55 UTC
When I attach a USBDM_JS16_JS16CWJ V1.1 to my computer using USB 3 and program it using JS16_Bootloader, the resulting flash contents are corrupt. When I connect it through a USB 2 hub (which is itself connected to the same USB 3 port), programming works as expected.

The Freescale bootloader enumerates correctly and consistently on both USB 2 and USB 3. JS16_Bootloader is able to find the device and program it without reporting an error in both configurations. However, after programming on USB 3, the device fails to enumerate as a USBDM device once I remove the BLMS jumper and reconnect it.

I used another USBDM to dump the contents of flash after an unsuccessful flash, and I saw many 32-byte sequences of 0xFF (i.e. unprogrammed flash) where there should have been program data. [flash-dump.zip](https://github.com/podonoghue/usbdm-eclipse-makefiles-build/files/3588800/flash-dump.zip) includes reads of the flash after two separate failed flashes, as well as the image I attempted to flash for reference. If you diff the files, you can see that entire rows of the flash are blank when they shouldn't be.

The JS16_Bootloader logs contain no hints. [Here](https://github.com/podonoghue/usbdm-eclipse-makefiles-build/files/3588807/JS16_Bootloader-bad.log) is a log of a USB 3 flash that failed. And [here](https://github.com/podonoghue/usbdm-eclipse-makefiles-build/files/3588810/JS16_Bootloader-good.log) is a log of several USB 2 flashes that succeeded. I stripped the timestamps, so you can just diff the two logs and see that the output for any given flash is identical between the two.

**Comment by podonoghue** [comment] 2019-09-12 06:10
Hi,

Yes I can confirm the problem with USB 3.
I have reviewed the bootloader code and can't see anything that is likely to be a problem e.g. timing related.  The code is pretty simple.

The program checks the result code after programming each 32-byte block so this would indicate that either the JS16 is not receiving the correct data i.e. it is programming 0xFF's OR it is not receiving some of the programming transactions at all - in which case the return code is simply a repeat of an earlier result and the block is simply unprogrammed.  I think the latter is more likely.
I suspect it is an issue with the JS16 ROM bootloader but I don't have any way of checking this.
A USB analyser would be required to figure out where the error is occurring.

I don't use the  checksum. It would be possible to add that but it would not actually solve the problem - it would simply report failure all the time on USB3.  It is not possible to check each transaction and retry as read-back is unavailable and AFAIK the checksum is for the whole Flash.

The firmware updater seem to have no problem with USB 3 after the bootloader is programmed but that uses my bootloader firmware on the JS16 so doesn't indicate much.

bye

**Comment by podonoghue** [comment] 2019-09-13 02:18
![USB No Retry 2019-09-13_11-34-29](https://user-images.githubusercontent.com/1848579/64833694-3d77bc00-d622-11e9-8eb9-025b695ac127.png)
![USB Retry 2019-09-13_11-34-29](https://user-images.githubusercontent.com/1848579/64833698-4072ac80-d622-11e9-9deb-8fd6da12b0eb.png)

I have had a look at the USB transactions using a logic analyser.
It appears  that all transactions succeed first-time on USB2.
On USB3 there are a number of NAKed transactions that are immediately retried and ACKed.
This should be acceptable though unexpected.  NAKes are used to throttle the USB transactions.  It would appear that the timing is different on the USB3 even when working at lower speeds.
~~[My conclusion is that the the USB firmware in the JS16 simply doesn't handle USB retransmissions correctly.]~~ - incorrect see below.
If this is the case there is not any thing I can do about it.
I will play a bit more but I am not hopeful.
I have attached example USB captures.  Note that the decoding incorrectly indicates a double-length data packet for the retry- it is actual the same data twice.  This is a bug in the analyser.

**Comment by tchebb** [comment] 2019-09-13 05:54
Thanks for such a thorough investigation! I also reviewed the code before filing this issue and didn't see anything wrong with it. So it does seem like a driver/firmware/hardware issue.

Are those two captures on the same timescale? I assume not, since there's more data in the second one. Can you tell if the USB clock rates are different between the two? Or is it a more subtle timing variation?

**Comment by podonoghue** [comment] 2019-09-14 04:53
Hi,

It looks like the retries are not relevant.
Matching up the transactions with the regions that failed to program doesn't show any correlation i.e. some blocks without  retries have failed and conversely , some block with retries are successful!

So - not any wiser.  The data seems to be transferred to the JS16 correctly, the handshake (0x01) is sent from the JS16 after each block is programmed but the data is incorrect.
I have attached example USB transactions with timestamps
[transaction.txt](https://github.com/podonoghue/usbdm-eclipse-makefiles-build/files/3612352/transaction.txt)

**Comment by podonoghue** [comment] 2022-05-31 07:00
I believe the JS16 ROM bootloader code has problems with USB3.  Since this is a chip level error there is not much that can be done.  Posting on Freescale.NXP forum did not elicit any information.
As mention above by @tchebb  a work-around is  (obviously) to use a USB2 port or interpose a USB2 hub.

**Closed as completed by podonoghue** 2022-05-31 07:00 UTC
